# Generated by Django 3.2.5 on 2022-03-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='knob',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='wkl',
        ),
        migrations.AddField(
            model_name='artisan',
            name='documentation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='accessories',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='carrying_case',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='layout',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='stabs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='switch',
            name='number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='build',
            name='keycap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.keycap'),
        ),
        migrations.AlterField(
            model_name='build',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.switch'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='plate',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
