# Generated by Django 3.2.5 on 2022-02-10 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='keyboard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.keyboard'),
        ),
        migrations.AlterField(
            model_name='build',
            name='keycap',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.keycap'),
        ),
        migrations.AlterField(
            model_name='build',
            name='switch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.switch'),
        ),
    ]
