# Generated by Django 3.2.5 on 2022-03-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220325_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='keycap',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='keycap',
            name='production',
            field=models.CharField(blank=True, choices=[('Doubleshot', 'Doubleshot'), ('Tripleshot', 'Tripleshot'), ('Dye-Sublimated', 'Dye-Sublimated'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='switch',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
