# Generated by Django 3.2.5 on 2022-03-29 14:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220325_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyboard',
            old_name='stabs',
            new_name='stabilizers',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='stabilizer_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='slug',
            field=models.SlugField(default=app.models.random_slug_string, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='slug',
            field=models.SlugField(default=app.models.random_slug_string, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='slug',
            field=models.SlugField(default=app.models.random_slug_string, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='slug',
            field=models.SlugField(default=app.models.random_slug_string, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='keycap',
            name='slug',
            field=models.SlugField(default=app.models.random_slug_string, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='slug',
            field=models.SlugField(default=app.models.random_slug_string, max_length=255, unique=True),
        ),
    ]
