# Generated by Django 3.2.5 on 2022-03-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220325_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyboard',
            old_name='stabs',
            new_name='stabilizers',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='stabilizer_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
